# Site settings
title: My Blog
email: mabast.m.ahmad@ieee.org
description: > # this means to ignore newlines until "baseurl:"
  This blog is for my researchs and studyings in AI & Bioinformatics fields. 
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: https://twitter.com/MabastNiga
github_username:  https://github.com/Mabast1

# Build settings
markdown: redcarpet
baseurl: /blog

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


